service_name = "Tricrow's personal website"
service_url = "https://www.tricrow.com/"
mail_reply_title = "お問い合わせありがとうございました"
mail_secret_key = "my-mail-address"
secrets_manager_region = "ap-northeast-1"
